name-template: 'docs-v$RESOLVED_VERSION'
tag-template: 'docs-v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'

template: |
  ## What's Changed
  $CHANGES

include-paths:
  - 'packages/docs/**'
